// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_DeleteLover from "./routes/api/DeleteLover.ts";
import * as $api_joke from "./routes/api/joke.ts";
import * as $delete from "./routes/delete.tsx";
import * as $delete_name_ from "./routes/delete/[name].tsx";
import * as $hobbies from "./routes/hobbies.tsx";
import * as $index from "./routes/index.tsx";
import * as $register from "./routes/register.tsx";
import * as $search_name_ from "./routes/search/[name].tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $DeleteLover from "./islands/DeleteLover.tsx";
import * as $Filtros from "./islands/Filtros.tsx";
import * as $RegisterForm from "./islands/RegisterForm.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/DeleteLover.ts": $api_DeleteLover,
    "./routes/api/joke.ts": $api_joke,
    "./routes/delete.tsx": $delete,
    "./routes/delete/[name].tsx": $delete_name_,
    "./routes/hobbies.tsx": $hobbies,
    "./routes/index.tsx": $index,
    "./routes/register.tsx": $register,
    "./routes/search/[name].tsx": $search_name_,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
    "./islands/DeleteLover.tsx": $DeleteLover,
    "./islands/Filtros.tsx": $Filtros,
    "./islands/RegisterForm.tsx": $RegisterForm,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
